binary_sensor:
  - platform: homeassistant
    id: tv_power
    name: tv_power
    entity_id: media_player.lg_webos_smart_tv
    internal: false
    on_state_change: 
      then:
        - logger.log: "tv state"
        - delay: 15s
        - script.execute: script_check_turn_off
#         - logger.log: "tv state"
#         - if:
#             condition:
#               - lambda: return id(tv_power_first_trigger);     
#             then:
#               - logger.log: "tv state first"
#               - globals.set:
#                   id: tv_power_first_trigger
#                   value: 'false'
#               - script.execute: script_startup
#             else:
#               - logger.log: "tv state not first"
#               - script.execute: script_check_turn_off

text_sensor:
  - platform: homeassistant
    id: amp_power
    name: amp_power
    entity_id: media_player.lounge_av_reciever
    internal: false
    on_value: 
      then:
        - logger.log: "amp state"
        - delay: 15s
        - script.execute: script_check_turn_off

