binary_sensor:
  - platform: homeassistant
    id: tv_power
    name: tv_power
    entity_id: media_player.lg_webos_smart_tv
    internal: false

text_sensor:
  - platform: homeassistant
    id: amp_power
    name: amp_power
    entity_id: media_player.lounge_av_reciever
    internal: false

