binary_sensor:
  - platform: homeassistant
    id: tv_power
    name: tv_power
    entity_id: media_player.lg_webos_smart_tv
    internal: false
    on_state_change: 
      then:
        - if:
            condition:
              - lambda: return id(glb_powered_up);     
            then:
              - script.execute: script_check_turn_off       
       


text_sensor:
  - platform: homeassistant
    id: amp_power
    name: amp_power
    entity_id: media_player.lounge_av_reciever
    internal: false
    on_value: 
      then:
        - if:
            condition:
              - lambda: return id(glb_powered_up);     
            then:
              - script.execute: script_check_turn_off    
