esphome:
  name: "remote-control-01"
  friendly_name: Remote Control
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: LIGHT
  output_power: 10dB  # Reduce WiFi power if signal is strong enough

packages:
  remote_package_files:  
    url: https://github.com/nilbogAus/The-Everything-Remote/
    path: YAML
    files: 
      - path: ESPHome YAML - v3.0.YAML
    ref: main
    refresh: 5s