script:
  - id: script_go_to_sleep
    then:
      - light.turn_on:
          id: LED
          effect: Blink
      - delay: 10s  
      - deep_sleep.enter: deep_sleep_ctrl
      - light.turn_off:
          id: LED  
  - id: script_startup
    then:
      - delay: 5s #wait for boot
      - light.turn_on: LED
      - delay: 1s #wait for boot
      - logger.log: "sending power short"
      - homeassistant.event:
          event: esphome.remote_button_pressed
          data: {button: "power", type: "single"}
  - id: script_check_turn_off
    then:
      - if:
          condition:
            - and:
              - binary_sensor.is_off: tv_power 
              - text_sensor.state:
                  id: amp_power
                  state: 'off'      
          then:
            - logger.log: "Go to sleep"
            - script.execute: script_go_to_sleep
          else:
            - logger.log: "stay awake"

deep_sleep:
  id: deep_sleep_ctrl 
  wakeup_pin:
    number: GPIO0
    inverted: true
    allow_other_uses: true

# interval: # backup power off shouldn't be needed
#   - interval: 30min
#     then:
#       - logger.log: "interval"
#       - script.execute: script_check_turn_off

light: 
  - platform: status_led
    name: "LED"
    id: LED
    pin: 
      number: GPIO13
      inverted: false
    effects:
      - strobe:
          name: Blink # 0.1s on, 2s off
          colors:
            - state: true
              brightness: 100%
              duration: 500ms
            - state: false
              duration: 500ms

# BUTTONS
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
      allow_other_uses: true
    name: "Power"
    id: power
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "power", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - logger.log: "Go to sleep"
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "power", type: "long"}
          - script.execute: script_go_to_sleep
            

  - platform: gpio
    pin:
      number: GPIO2
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Back"
    id: back
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "back", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "back", type: "long"}

  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Home"
    id: home
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "home", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "home", type: "long"}

  - platform: gpio
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Play Pause"
    id: play_pause
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "play_pause", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "play_pause", type: "long"}

  - platform: gpio
    pin:
      number: GPIO18
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Up"
    id: up
    internal: true
    on_state:
      - while: 
          condition:
            binary_sensor.is_on: up 
          then:
            - homeassistant.event:
                event: esphome.remote_button_pressed
                data: {button: "up", type: "repeat"}
            - delay: 200ms # Adjust the delay for desired repeat speed

  - platform: gpio
    pin:
      number: GPIO19
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Left"
    id: left
    internal: true
    on_state:
      - while: 
          condition:
            binary_sensor.is_on: left 
          then:
            - homeassistant.event:
                event: esphome.remote_button_pressed
                data: {button: "left", type: "repeat"}
            - delay: 200ms # Adjust the delay for desired repeat speed

  - platform: gpio
    pin:
      number: GPIO22
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Select"
    id: select_button 
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "select_button", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "select_button", type: "long"}

  - platform: gpio
    pin:
      number: GPIO23
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Right"
    id: right
    internal: true
    on_state:
      - while: 
          condition:
            binary_sensor.is_on: right 
          then:
            - homeassistant.event:
                event: esphome.remote_button_pressed
                data: {button: "right", type: "repeat"}
            - delay: 200ms # Adjust the delay for desired repeat speed

  - platform: gpio
    pin:
      number: GPIO25
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Down"
    id: down
    internal: true
    on_state:
      - while: 
          condition:
            binary_sensor.is_on: down 
          then:
            - homeassistant.event:
                event: esphome.remote_button_pressed
                data: {button: "down", type: "repeat"}
            - delay: 200ms # Adjust the delay for desired repeat speed

  - platform: gpio
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Volume Up"
    id: volume_up
    internal: true
    on_state:
      - while: 
          condition:
            binary_sensor.is_on: volume_up 
          then:
            - homeassistant.event:
                event: esphome.remote_button_pressed
                data: {button: "volume_up", type: "repeat"}
            - delay: 200ms # Adjust the delay for desired repeat speed

  - platform: gpio
    pin:
      number: GPIO36
      mode:
        input: true
      inverted: true
    name: "Mute"
    id: mute
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "mute", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "mute", type: "long"}

  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Channel Up"
    id: channel_up
    internal: true
    on_state:
      - while: 
          condition:
            binary_sensor.is_on: channel_up 
          then:
            - homeassistant.event:
                event: esphome.remote_button_pressed
                data: {button: "channel_up", type: "repeat"}
            - delay: 200ms # Adjust the delay for desired repeat speed


  - platform: gpio
    pin:
      number: GPIO15
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Volume Down"
    id: volume_down
    internal: true
    on_state:
      - while: 
          condition:
            binary_sensor.is_on: volume_down 
          then:
            - homeassistant.event:
                event: esphome.remote_button_pressed
                data: {button: "volume_down", type: "repeat"}
            - delay: 200ms # Adjust the delay for desired repeat speed

  - platform: gpio
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Settings"
    id: settings
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "settings", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "settings", type: "long"}

  - platform: gpio
    pin:
      number: GPIO17
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Channel Down"
    id: channel_down
    internal: true
    on_state:
      - while: 
          condition:
            binary_sensor.is_on: channel_down 
          then:
            - homeassistant.event:
                event: esphome.remote_button_pressed
                data: {button: "channel_down", type: "repeat"}
            - delay: 200ms # Adjust the delay for desired repeat speed
            
  - platform: gpio
    pin:
      number: GPIO32
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Shortcut 3"
    id: shortcut_3
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "shortcut_3", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "shortcut_3", type: "long"}

  - platform: gpio
    pin:
      number: GPIO33
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Shortcut 4"
    id: shortcut_4
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "shortcut_4", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "shortcut_4", type: "long"}

  - platform: gpio
    pin:
      number: GPIO26
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Brightness Down"
    id: brightness_down
    internal: false 
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "brightness_down", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "brightness_down", type: "long"}

  - platform: gpio
    pin:
      number: GPIO27
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Brightness Up"
    id: brightness_up
    internal: false 
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "brightness_up", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "brightness_up", type: "long"}

  - platform: gpio
    pin:
      number: GPIO34
      mode:
        input: true
      inverted: true
    name: "Shortcut 1"
    id: shortcut_1
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "shortcut_1", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "shortcut_1", type: "long"}

  - platform: gpio
    pin:
      number: GPIO35
      mode:
        input: true
      inverted: true
    name: "Shortcut 2"
    id: shortcut_2
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 350ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "shortcut_2", type: "single"}
      - timing:
          - ON for at least 500ms
        then:
          - homeassistant.event:
              event: esphome.remote_button_pressed
              data: {button: "shortcut_2", type: "long"}
